### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [galla192/project5#1]
I'm getting an error [on line 2 of `app.rb`](https://github.com/galla192/project5/blob/master/app.rb#L2) when I test this locally. `require` lines must use the same format as what you'd use when including the gem in a Gemfile, which typically will not have any capital letters. Can you fix this, ensure it runs properly, then push up again?

**Comment by galla192** [comment]
Sorry about the delay, should be fixed now

Quoting Chris Fritz notifications@github.com:

**Comment by chrisvfritz** [comment]
:+1: Looking much better!
